// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzCT7jCamYbfJYi1KkdZdkvCbmHKZUAzo',
    appId: '1:637654941054:web:3b9433907b35cf3155072f',
    messagingSenderId: '637654941054',
    projectId: 'flutter-college-project',
    authDomain: 'flutter-college-project.firebaseapp.com',
    storageBucket: 'flutter-college-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9NjVInQr673I6wBW8IHVzXRvQ3MvrlxE',
    appId: '1:637654941054:android:a4c66ffda524ee4855072f',
    messagingSenderId: '637654941054',
    projectId: 'flutter-college-project',
    storageBucket: 'flutter-college-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARO2RzcezYG-jD2bmqBDMyH1DMYnieZGc',
    appId: '1:637654941054:ios:a8c159fc36d4062855072f',
    messagingSenderId: '637654941054',
    projectId: 'flutter-college-project',
    storageBucket: 'flutter-college-project.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotesApp',
  );
}
